pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone git@bitbucket.org:scratchcourse/scratchcourse.git
          - cd scratchcourse
          - git remote add upstream git@github.com:a-leandra/scratch-course.git
          - git push upstream main
          - git push --tags upstream
          - git remote set-url origin git@github.com:a-leandra/scratch-course.git
          - git push --mirror