pipelines:
  default:
    - step:
        name: Sync GitHub Mirror
        image: alpine/git:latest
        clone:
          enabled: false
        script:
          - git clone git@bitbucket.org:scratchcourse/scratchcourse.git
          - cd scratchcourse
          - git push --mirror git@github.com:a-leandra/scratch-course.git