[[redirects]]
from = "/api/users/login"
to = "https://scratchcourse-backend.onrender.com/api/users/login"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/" 
to = "https://scratchcourse-backend.onrender.com/api/users"
force = true
status = 202
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/profil" 
to = "https://scratchcourse-backend.onrender.com/api/users/profil"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/tasks/:email" 
to = "https://scratchcourse-backend.onrender.com/api/users/tasks/:email"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/requestPasswordReset" 
to = "https://scratchcourse-backend.onrender.com/api/users/requestPasswordReset"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/activateAccount" 
to = "https://scratchcourse-backend.onrender.com/api/users/activateAccount"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/resetPassword" 
to = "https://scratchcourse-backend.onrender.com/api/users/resetPassword"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/mapa-poziomow" 
to = "/mapa-poziomow"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/groups/:email" 
to = "https://scratchcourse-backend.onrender.com/groups/:email"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/:email" 
to = "https://scratchcourse-backend.onrender.com/api/users/:email"
force = true
status = 200
headers = {X-From = "Netlify"}