[[redirects]]
from = "/api/users/login" 
to = "https://scratchcourse-backend.onrender.com/users/login"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/" 
to = "https://scratchcourse-backend.onrender.com/users"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/profil" 
to = "https://scratchcourse-backend.onrender.com/users/profil"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/task/*" 
to = "https://scratchcourse-backend.onrender.com/users/task/:splat"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/api/users/requestPasswordReset" 
to = "https://scratchcourse-backend.onrender.com/users/requestPasswordReset"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/mapa-poziomow" 
to = "/mapa-poziomow"
force = true
status = 200
headers = {X-From = "Netlify"}

[[redirects]]
from = "/*" 
to = "/glowna"
force = true
status = 200
headers = {X-From = "Netlify"}